[ntfy]
enabled = false
server = "https://ntfy.sh"
topic = "your-topic-name"
username = ""
password = ""
priority = "high"
tags = [
    "thermometer",
]

[voice]
enabled = true

[data_recording]
enabled = true
path = "data/temperature_logs.db"
